### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by walter-erquinigo**
assignment 2

### CODE REVIEW

**Comment by neuralinfo** [comment]
You have to perform a pull request from a dev branch to the master branch of your own repo, NOT to the MIDS-W205/Assignments master repo

**Comment by walter-erquinigo** [comment]
so I send a new pull request, right?

**Comment by neuralinfo** [comment]
Yes, if you're having trouble, follow the instructions here step by step:
https://github.com/MIDS-W205/Assignments/blob/master/README.md

**Comment by walter-erquinigo** [comment]
I've just done that.
New pull request: https://github.com/a20012251/MIDS-W205_A2/pull/1

thanks!

2015-06-24 14:09 GMT-07:00 MIDS-W205 notifications@github.com:

> Yes, if you're having trouble, follow the instructions here step by step:
> https://github.com/MIDS-W205/Assignments/blob/master/README.md
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MIDS-W205/Assignments/pull/13#issuecomment-115013138.

## 

Walter Erquínigo Pezo

Every problem has a simple, fast and wrong solution.

**Pull request closed without merging**
